/*
 * This file is a part of the Lesson 1 project.
 */

package em.zed.androidchat.backend.firebase;

public final class Schema {

    /* root :: {
     *   users :: Map EmailKey {
     *     email :: str
     *     online :: bool
     *     contacts :: Map EmailKey bool
     *   }
     *   chats :: Map PairKey (Map Uid {
     *     msg :: str
     *     sender :: EmailKey
     *     sentByMe :: bool
     *   })
     * }
     * where
     *   EmailKey = email with illegal chars replaced by underscore
     *   PairKey = 2 EmailKeys connected by 3 underscores
     *   Uid = autogenerated string
     */

    public static final String USERS = "users";
    public static final String CONTACTS = "contacts";
    public static final String EMAIL = "email";
    public static final String ONLINE = "online";

    public static String legalize(String key) {
        return key.replaceAll("[.$#\\[\\]]", "_");
    }

    public static String illegalize(String key) {
        return key.replaceAll("_", ".");
    }

    public static String pathTo(String first, String... segments) {
        StringBuilder sb = new StringBuilder("/").append(first);
        for (String s : segments) {
            sb.append('/').append(s);
        }
        return sb.toString();
    }

    private Schema() {}

}
